import { registerEnumType } from '@nestjs/graphql'

export enum MentoringTopic {
  'basicProgrammingSkills' = 'basicProgrammingSkills',
  'htmlCss' = 'htmlCss',
  'javascript' = 'javascript',
  'react' = 'react',
  'java' = 'java',
  'python' = 'python',
  'dataAnalytics' = 'dataAnalytics',
  'machineLearning' = 'machineLearning',
  'mobileDevelopmentIos' = 'mobileDevelopmentIos',
  'mobileDevelopmentAndroid' = 'mobileDevelopmentAndroid',
  'salesforce' = 'salesforce',
  'devOpsCloud' = 'devOpsCloud',
  'iot' = 'iot',
  'computerNetworking' = 'computerNetworking',
  'blockchain' = 'blockchain',
  'productManagement' = 'productManagement',
  'projectManagement' = 'projectManagement',
  'digitalMarketing' = 'digitalMarketing',
  'businessDevelopment' = 'businessDevelopment',
  'sales' = 'sales',
  'qualityAssurance' = 'qualityAssurance',
  'basicGerman' = 'basicGerman',
  'businessGerman' = 'businessGerman',
  'english' = 'english',
  'swedish' = 'swedish',
  'graphicDesign' = 'graphicDesign',
  'userInterfaceDesign' = 'userInterfaceDesign',
  'userExperienceDesign' = 'userExperienceDesign',
  'motivationAndEncouragement' = 'motivationAndEncouragement',
  'friendAndHelp' = 'friendAndHelp',
  'dontKnowYet' = 'dontKnowYet',
  'careerOrientationAndPlanning' = 'careerOrientationAndPlanning',
  'internshipOrWorkingStudent' = 'internshipOrWorkingStudent',
  'jobSearch' = 'jobSearch',
  'jobApplicationsCvPreparationEnglish' = 'jobApplicationsCvPreparationEnglish',
  'jobApplicationsCvPreparationGerman' = 'jobApplicationsCvPreparationGerman',
  'interviewPreparation' = 'interviewPreparation',
  'codingChallengePreparation' = 'codingChallengePreparation',
  'buildingProfessionalNetwork' = 'buildingProfessionalNetwork',
  'entrepreneurship' = 'entrepreneurship',
  'freelancing' = 'freelancing',
}
registerEnumType(MentoringTopic, { name: 'MentoringTopic' })
