import { registerEnumType } from '@nestjs/graphql'

export enum RediCourse {
  introJava = 'introJava',
  intermediateJava = 'intermediateJava',
  advancedJava = 'advancedJava',
  cloudComputing = 'cloudComputing',
  pythonFoundation = 'pythonFoundation',
  dataAnalytics = 'dataAnalytics',
  salesforceFundamentals = 'salesforceFundamentals',
  introComputerScience = 'introComputerScience',
  htmlCss = 'htmlCss',
  javaScript = 'javaScript',
  react = 'react',
  iot = 'iot',
  codingFundamentals = 'codingFundamentals',
  uiUxDesignBasics = 'uiUxDesignBasics',
  uiUxDesignIntermediate = 'uiUxDesignIntermediate',
  alumni = 'alumni',
  hamburg_htmlCss = 'hamburg_htmlCss',
  hamburg_introComputerScience = 'hamburg_introComputerScience',
  hamburg_uxUiDesignBasics = 'hamburg_uxUiDesignBasics',
  munich_introComputerScience = 'munich_introComputerScience',
  munich_pythonIntermediate = 'munich_pythonIntermediate',
  munich_frontend1 = 'munich_frontend1',
  munich_frontend2 = 'munich_frontend2',
  munich_dataAnalytics2 = 'munich_dataAnalytics2',
  munich_backend2 = 'munich_backend2',
  munich_uxUiDesign = 'munich_uxUiDesign',
  munich_cloudComputing = 'munich_cloudComputing',
  munich_cloudComputingAdvance = 'munich_cloudComputingAdvance',
  munich_dataStructuresAlgorithmsWithGoogle = 'munich_dataStructuresAlgorithmsWithGoogle',
  munich_alumni = 'munich_alumni',
  nrw_htmlCss = 'nrw_htmlCss',
  nrw_javascript = 'nrw_javascript',
  nrw_uxDesign = 'nrw_uxDesign',
  nrw_pythonIntroduction = 'nrw_pythonIntroduction',
  nrw_dataAnalytics = 'nrw_dataAnalytics',
  nrw_machineLearning = 'nrw_machineLearning',
  nrw_infrastructureBasics = 'nrw_infrastructureBasics',
  nrw_cloudComputing = 'nrw_cloudComputing',
  nrw_iot = 'nrw_iot',
  nrw_alumni = 'nrw_alumni',
}
registerEnumType(RediCourse, { name: 'RediCourse' })
