import { registerEnumType } from '@nestjs/graphql'

export enum TpDesiredPosition {
  administrativeAssistant = 'administrativeAssistant',
  agileScrumCoach = 'agileScrumCoach',
  azureSpecialist = 'azureSpecialist',
  backendDeveloper = 'backendDeveloper',
  blockchainDeveloper = 'blockchainDeveloper',
  businessAnalyst = 'businessAnalyst',
  cloudEngineer = 'cloudEngineer',
  cloudSpecialist = 'cloudSpecialist',
  dataAnalyst = 'dataAnalyst',
  dataScientist = 'dataScientist',
  devOpsSpecialist = 'devOpsSpecialist',
  digitalMarketer = 'digitalMarketer',
  embeddedSystemsEngineer = 'embeddedSystemsEngineer',
  frontendDeveloper = 'frontendDeveloper',
  fullstackDeveloper = 'fullstackDeveloper',
  hardwareDeveloper = 'hardwareDeveloper',
  iotDeveloper = 'iotDeveloper',
  itAdministrator = 'itAdministrator',
  itSpecialist = 'itSpecialist',
  itSupportTechnician = 'itSupportTechnician',
  javaDeveloper = 'javaDeveloper',
  linuxSystemAdministrator = 'linuxSystemAdministrator',
  marketingAssistant = 'marketingAssistant',
  mobileDeveloperAndroid = 'mobileDeveloperAndroid',
  mobileDeveloperIos = 'mobileDeveloperIos',
  nodeJsDeveloper = 'nodeJsDeveloper',
  operationsManager = 'operationsManager',
  productDesigner = 'productDesigner',
  productManager = 'productManager',
  projectAssistant = 'projectAssistant',
  projectManager = 'projectManager',
  pythonDeveloper = 'pythonDeveloper',
  qaEngineer = 'qaEngineer',
  reactDeveloper = 'reactDeveloper',
  requirementsEngineer = 'requirementsEngineer',
  salesforceAdministrator = 'salesforceAdministrator',
  salesManager = 'salesManager',
  securityAdministrator = 'securityAdministrator',
  seoManager = 'seoManager',
  systemEngineer = 'systemEngineer',
  technicalArchitect = 'technicalArchitect',
  uiDesigner = 'uiDesigner',
  uiDeveloper = 'uiDeveloper',
  uiUxDesigner = 'uiUxDesigner',
  usabilityengineer = 'usabilityengineer',
  userResearcher = 'userResearcher',
  uxDesigner = 'uxDesigner',
}

registerEnumType(TpDesiredPosition, { name: 'TpDesiredPosition' })
