import { registerEnumType } from '@nestjs/graphql'

export enum FederalState {
  BADEN_WUERTTEMBERG = 'BADEN_WUERTTEMBERG',
  BAYERN = 'BAYERN',
  BERLIN = 'BERLIN',
  BRANDENBURG = 'BRANDENBURG',
  BREMEN = 'BREMEN',
  HAMBURG = 'HAMBURG',
  HESSEN = 'HESSEN',
  MECKLENBURG_VORPOMMERN = 'MECKLENBURG_VORPOMMERN',
  NIEDERSACHSEN = 'NIEDERSACHSEN',
  NORDRHEIN_WESTFALEN = 'NORDRHEIN_WESTFALEN',
  RHEINLAND_PFALZ = 'RHEINLAND_PFALZ',
  SAARLAND = 'SAARLAND',
  SACHSEN = 'SACHSEN',
  SACHSEN_ANHALT = 'SACHSEN_ANHALT',
  SCHLESWIG_HOLSTEIN = 'SCHLESWIG_HOLSTEIN',
  THUERINGEN = 'THUERINGEN',
  OUTSIDE_GERMANY = 'OUTSIDE_GERMANY',
}
registerEnumType(FederalState, { name: 'FederalState' })
