export * from './tp-jobseeker-cv-language-record.entity'
export * from './tp-jobseeker-cv-language-record.entityprops'
export * from './tp-jobseeker-cv-language-record.mapper'
export * from './tp-jobseeker-cv-language.record'
export * from './tp-jobseeker-cv-language.recordprops'
