name: License Checker

on:
  pull_request:
    paths:
      - 'yarn.lock'

jobs:
  license-check:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # You can specify the required Node.js version

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Install license-checker globally
      - name: Install license-checker
        run: npm install -g license-checker

      # Generate license report
      - name: Generate license report
        run: |
          mkdir -p license-reports
          license-checker --json > license-reports/license-report.json

      # Upload license report as an artifact
      - name: Upload license report
        uses: actions/upload-artifact@v3
        with:
          name: license-report
          path: license-reports/license-report.json
